// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bazaDanych.Models;

#nullable disable

namespace bazaDanych.Migrations
{
    [DbContext(typeof(BazaDbContext))]
    partial class BazaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bazaDanych.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WpisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WpisId");

                    b.ToTable("Filmy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Opis = "Dziewczynka zaprzyjaznia sie z kosmita",
                            Tytul = "Lilo i stich",
                            WpisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Opis = " 24 nastolatkowie walcza na smierc i zycie umieraja ",
                            Tytul = "Igrzyska Śmierci",
                            WpisId = 2
                        },
                        new
                        {
                            Id = 3,
                            Opis = "O 3 wiewiorkach ktore spiewaja ",
                            Tytul = "Alwin i Wiewiórki",
                            WpisId = 3
                        },
                        new
                        {
                            Id = 4,
                            Opis = "Bohaterowie proboja powstrzymac zagrozenie na skale wszechswiata",
                            Tytul = "Infinity war",
                            WpisId = 4
                        });
                });

            modelBuilder.Entity("bazaDanych.Models.Wpis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<string>("Recenzje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wpisy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ocena = 7,
                            Recenzje = "Fajne"
                        },
                        new
                        {
                            Id = 2,
                            Ocena = 10,
                            Recenzje = "Mega mocne"
                        },
                        new
                        {
                            Id = 3,
                            Ocena = 2,
                            Recenzje = "Slabe"
                        },
                        new
                        {
                            Id = 4,
                            Ocena = 5,
                            Recenzje = "Moze byc"
                        });
                });

            modelBuilder.Entity("bazaDanych.Models.Film", b =>
                {
                    b.HasOne("bazaDanych.Models.Wpis", "Wpis")
                        .WithMany()
                        .HasForeignKey("WpisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Wpis");
                });
#pragma warning restore 612, 618
        }
    }
}
